malasakit-django/cafe/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView, RedirectView
from django.views.i18n import JavaScriptCatalog

from pcari.admin import site
from pcari.urls import api_urlpatterns

# pylint: disable=invalid-name
urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('pcari:landing')), name='to-landing'),
    # Service worker script must be served from the `URL_ROOT` for security reasons
    url(r'^sw.js$',
        TemplateView.as_view(template_name='sw.js', content_type='application/javascript'),
        name='service-worker'),

    # Admin site
    url(r'^admin/', site.urls),
    url(r'^admin/password_reset/$', auth_views.password_reset,
        name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,
        name='password_reset_complete'),

    url(r'^api/', include(api_urlpatterns)),  # AJAX endpoints
]

urlpatterns += i18n_patterns(
    url(r'', include('pcari.urls')),
    url(r'^feature-phone/', include('feature_phone.urls')),
    # Translations for JavaScript code
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers
handler404 = 'pcari.views.handle_page_not_found'
handler500 = 'pcari.views.handle_internal_server_error'

malasakit-django/pcari/urls.py
"""
This module defines how URLs should route to views.
"""

from __future__ import unicode_literals

from django.urls import reverse_lazy
from django.conf.urls import url
from django.views.generic.base import RedirectView

from pcari import views

# pylint: disable=invalid-name
app_name = 'pcari'

urlpatterns = [
    # User-facing views
    url(r'^$', RedirectView.as_view(url=reverse_lazy('pcari:landing')), name='index'),
    url(r'^landing/$', views.landing, name='landing'),
    url(r'^personal-information/$',
        views.CSRFTemplateView.as_view(template_name='personal-information.html'),
        name='personal-information'),
    url(r'^quantitative-questions/$',
        views.CSRFTemplateView.as_view(template_name='quantitative-questions.html'),
        name='quantitative-questions'),
    url(r'^rate-comments/$',
        views.CSRFTemplateView.as_view(template_name='rate-comments.html'),
        name='rate-comments'),
    url(r'^qualitative-questions/$', views.qualitative_questions,
        name='qualitative-questions'),
    url(r'^peer-responses/$', views.peer_responses, name='peer-responses'),
    url(r'^end/$', views.CSRFTemplateView.as_view(template_name='end.html'), name='end'),
    url(r'^about/$', views.CSRFTemplateView.as_view(template_name='about.html'),
        name='about'),
]

api_urlpatterns = [
    url(r'^fetch/comments/$', views.fetch_comments, name='fetch-comments'),
    url(r'^fetch/quantitative-questions/$', views.fetch_quantitative_questions,
        name='fetch-quantitative-questions'),
    url(r'^fetch/option-questions/$', views.fetch_option_questions,
        name='fetch-option-questions'),
    url(r'^fetch/qualitative-questions/$', views.fetch_qualitative_questions,
        name='fetch-qualitative-questions'),
    url(r'^fetch/question-ratings/$', views.fetch_question_ratings,
        name='fetch-question-ratings'),
    url(r'^fetch/locations/$', views.fetch_locations, name='fetch-locations'),
    url(r'^save-response/$', views.save_response, name='save-response'),
]

malasakit-django/pcari/views.py
"""
This module defines the application's views, which are needed to render pages.

These views can be broadly categorized into two groups:
    * **API endpoints** that can dynamically send and receive data (typically
      as `JSON <http://www.json.org/>`_). The client can use these endpoints to
      operate asynchronously.
    * **HTML pages** that show up to users. These pages are typically largely
      static and lend themselves to caching by service workers.

References:
  * `Django Introduction to Views <https://docs.djangoproject.com/en/dev/topics/http/views/>`_
  * `View Decorators <https://docs.djangoproject.com/en/dev/topics/http/decorators/>`_
  * `Creating Files for Download <https://docs.djangoproject.com/en/dev/howto/outputting-csv/>`_
"""

from __future__ import unicode_literals
import datetime
import logging
import json
import mimetypes
import random
import time
from uuid import UUID

import decorator
from django.conf import settings
from django.db.models import OneToOneRel
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_GET, require_POST
from django.views.generic.base import TemplateView
from django.utils import translation
from django.utils.decorators import method_decorator
from django.utils.html import escape as escape_html
from django.utils.translation import ugettext_lazy as _, ugettext
import numpy as np
from openpyxl import Workbook
import unicodecsv as csv

from pcari.models import Respondent, Location
from pcari.models import QuantitativeQuestion, OptionQuestion, QualitativeQuestion
from pcari.models import Comment, CommentRating, QuantitativeQuestionRating, OptionQuestionChoice
from pcari.models import get_concrete_fields

__all__ = [
    'generate_ratings_matrix',
    'normalize_ratings_matrix',
    'calculate_principal_components',
    'fetch_comments',
    'fetch_quantitative_questions',
    'fetch_option_questions',
    'fetch_qualitative_questions',
    'fetch_question_ratings',
    'save_response',
    'export_data',
    'landing',
    'qualitative_questions',
    'peer_responses',
    'handle_page_not_found',
    'handle_internal_server_error',
]

LOGGER = logging.getLogger('pcari')


@decorator.decorator
def profile(function, *args, **kwargs):
    """
    Log the runtime of a function call.

    Args:
        function: The callable to profile.
        args: Additional positional arguments to ``function``.
        kwargs: Additional keyword arguments to ``function``.

    Returns:
        The result of applying ``function`` to ``args`` and ``kwargs``.
    """
    start_time = time.time()
    result = function(*args, **kwargs)
    end_time = time.time()
    time_elapsed = end_time - start_time
    LOGGER.log(logging.DEBUG, 'Call to "%s" took %.3f seconds',
               function.__name__, time_elapsed)
    return result


@profile
def generate_ratings_matrix():
    """
    Fetch quantitative question ratings in the form of a :mod:`numpy` matrix.

    Each row in the matrix represents the ratings of one respondent, and each
    column represents the ratings for one question.

    Returns:
        tuple: Tuple of three items:
            * ``respondent_id_map`` (`dict`): A length-`m` map from respondent
              identifiers to matrix row indicies.
            * ``question_id_map`` (`dict`): A length-`n` map from quantitative
              question identifiers to matrix column indicies.
            * ``ratings_matrix`` (`numpy.ndarray`): An `m` by `n` NumPy array
              of ratings.

        Only active respondents, active questions, and active ratings are used
        (see :attr:`pcari.models.History.active`).
    """
    respondent_ids = Respondent.objects.values_list('id', flat=True)
    question_ids = QuantitativeQuestion.objects.values_list('id', flat=True)

    respondent_id_map = {key: index for index, key in enumerate(respondent_ids)}
    question_id_map = {key: index for index, key in enumerate(question_ids)}

    shape = len(respondent_id_map), len(question_id_map)
    ratings_matrix = np.full(shape, np.nan)

    values = QuantitativeQuestionRating.objects.filter(question__enabled=True)
    features = 'respondent_id', 'question_id', 'score'
    values = values.exclude(score=QuantitativeQuestionRating.SKIPPED).values_list(*features)

    for respondent_id, question_id, score in values:
        row_index = respondent_id_map[respondent_id]
        column_index = question_id_map[question_id]
        ratings_matrix[row_index, column_index] = score

    return respondent_id_map, question_id_map, ratings_matrix


@profile
def normalize_ratings_matrix(ratings_matrix):
    """
    Normalize a ratings matrix so the ellipsoid of ratings is centered at the
    origin, and missing values are imputed with zero. (That is, the mean of the
    column before centering.)

    Args:
        ratings_matrix (numpy.ndarray): An `m` by `n` matrix of ratings (as
            provided by :func:`generate_ratings_matrix`).

    Returns:
        numpy.ndarray: An `m` by `n` matrix of normalized ratings with no
        ``np.nan`` values.
    """
    means_of_columns = np.nanmean(ratings_matrix, axis=0)
    return np.nan_to_num(ratings_matrix - means_of_columns)


@profile
def calculate_principal_components(normalized_ratings, num_components=2):
    """
    Calculate the principal components of a normalized ratings matrix.

    Args:
        normalized_ratings (numpy.ndarray): An `m` by `n` normalized ratings
            matrix (as provided by :func:`normalize_ratings_matrix`).
        num_components (int): The number of principal components to select
            (`p`).

    Returns:
        numpy.ndarray: A `p` by `n` matrix whose rows are principal components.
    """
    _, _, covariance_matrix = np.linalg.svd(normalized_ratings, full_matrices=False)
    return covariance_matrix[:num_components]


@profile
@require_GET
def fetch_comments(request):
    """
    Fetch a list of comments as JSON.

    Args:
        request: May contain a `limit` GET parameter that specifies how many
            comments to get (by default: 300). Very high limits may decrease
            performance noticeably.

    Returns:
        A ``JsonResponse`` containing an JSON object of the form::

            {
                "<comment.id>": {
                    "msg": "<comment.message>",
                    "sem": <comment.score_sem>,
                    "pos": <author question ratings projection>,
                    "tag": "<comment.tag>",
                    "qid": <comment.question_id>
                },
                ...
            }

        The ``pos`` property is calculated by projecting the quantitative
        question ratings vector of the comment's author onto the first two
        principal components of the question ratings dataset (from
        :func:`calculate_principal_components`). This property is a list
        containing two numbers: the first and second projections, respectively.
    """
    try:
        limit = int(request.GET.get('limit', unicode(settings.DEFAULT_COMMENT_LIMIT)))
    except ValueError as error:
        return HttpResponseBadRequest(unicode(error))

    comments = (Comment.objects.filter(original=None, question__enabled=True, flagged=False)
                .exclude(message='').all())
    if len(comments) > limit:
        comments = random.sample(comments, limit)

    respondent_id_map, _, ratings = generate_ratings_matrix()
    data_in_every_column = all(np.count_nonzero(~np.isnan(ratings[:, i]))
                               for i in range(ratings.shape[1])) and ratings.size
    if data_in_every_column:
        normalized_ratings = normalize_ratings_matrix(ratings)
        components = calculate_principal_components(normalized_ratings, 2)

    data = {}
    for comment in comments:
        standard_error = comment.score_sem
        row_index = respondent_id_map[comment.respondent.id]
        position = [0, 0]
        if data_in_every_column:
            position = list(np.round(components.dot(normalized_ratings[row_index, :]), 3))

        # Projects the ratings by this comment's author onto the first two
        # principal components to generate the position (`pos`).
        if standard_error is None:
            standard_error = settings.DEFAULT_STANDARD_ERROR
        data[unicode(comment.id)] = {
            'msg': escape_html(comment.message),
            'sem': round(standard_error, 3),
            'pos': position,
            'tag': escape_html(comment.tag),
            'qid': comment.question_id
        }

    return JsonResponse(data)


def translate(text, language_code):
    with translation.override(language_code):
        return ugettext(text)


@profile
@require_GET
def fetch_qualitative_questions(request):
    """
    Fetch qualitative question data as JSON.

    Args:
        request: This parameter is ignored.

    Returns:
        A ``JsonResponse`` containing a JSON object of the form::

            {
                "<question.id>": {
                    "<language-code>": "<translated question.prompt>",
                    ...
                },
                ...
            }

        Each language code is obtained from ``settings.LANGUAGES``.
    """
    # pylint: disable=unused-argument
    return JsonResponse({
        unicode(question.id): {
            code: escape_html(translate(question.prompt, code))
            for code, _ in settings.LANGUAGES
        } for question in QualitativeQuestion.objects.iterator()
    })


@profile
@require_GET
def fetch_quantitative_questions(request):
    """
    Fetch quantitative question data as JSON.

    Args:
        request: This parameter is ignored.

    Returns:
        A ``JsonResponse`` containing a JSON object of the form::

            [
                {
                    "id": <question.id>,

malasakit-django/pcari/templates/base.html
{% load i18n %}
{% load static %}
{% load localize_url %}
{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block static-assets %}
      <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% url 'javascript-catalog' %}"></script>
      <script src="{% static 'js/client.js' %}"></script>
      <script src="{% static 'js/uuid4.js' %}"></script>
      {% if settings.SERVICE_WORKERS %}
        <script src="{% static 'js/sw-bootstrap.js' %}"></script>
      {% endif %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}

    <title>Kalahok &bullet; {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% get_available_languages as languages %}
    {% if languages|length > 1 %}
      <nav>
        <div class="container">
          <ul id="languages">
            {% for code, name in languages %}
              <li>
                <a href="{{ request.path|localize_url:code }}">{{ name }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
      </nav>
    {% endif %}
    <header>
      <div class="container">
        <h1 id="main-heading">{% block main-heading %}HAPAG-KAINAN{% endblock %}</h1>
      </div>
    </header>
    <main>
      <div class="container">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    <footer>
      <div class="container">
        <hr>
        <p id="footnote">
          {% block footnote %}
            {% blocktrans trimmed %}
              This site uses the Collective Assessment and Feedback Engine
              (CAFÉ).
            {% endblocktrans %}
          {% endblock %}
        </p>
      </div>
    </footer>
  </body>
</html>

malasakit-django/pcari/templates/base_with_links.html
{% extends 'base.html' %}

{% load i18n %}

{% block footnote %}
  {% url 'pcari:about' as about_url %}
  {% blocktrans trimmed %}
    This site uses the <a href="http://cafesystem.org/" target="_blank">Collective Assessment and Feedback Engine (CAFÉ)</a>.
    Learn more about <a href="{{ about_url }}">CAFÉ</a>.
  {% endblocktrans %}
{% endblock %}

malasakit-django/pcari/templates/landing.html
{% extends 'base_with_links.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'Welcome' %}{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      $('#next').on('click', function() {
        startResponse();
        Resource.delete('selected-comments');
      });
    });
  </script>
{% endblock %}

{% block content %}
  <div>
    <p class="center">

    </p>
    <p class="center">
      {% blocktrans trimmed %}
        {{ num_responses }} na ang mga kumain at nagbigay ng kanilang karanasan.
      {% endblocktrans %}
    </p>
    <p class="center">
      {% trans 'Ibahagi mo na rin ang iyong karanasan!' %}
    </p>
    <img src="{% static 'img/landing' %}">

  <p align="justify">
  Ang ​ HAPAG-KAINAN ​ ay isa lang sa mga toolkit na binuo sa ilalim ng E-Participation Project ng National University at University of California, Berkeley. Ang proyektong ito ay suportado ng Commission on Higher Education (CHED) sa pamamagitan ng Philippine-California Advanced Research Institutes (PCARI). Sa pagsagot nitong toolkit, boluntaryo kayong nakikibahagi sa gawaing ito at batid niyo na lahat ng mga impormasyong inyong ibibigay ay maaaring gamitin upang higit pang mapabuti ang mga pasilidad at serbisyo sa NU cafeteria.
  </p>
  </div>
  {% url 'pcari:personal-information' as next_link %}
  {% trans 'Simulan' as next_label %}
  {% include 'nav-buttons.html' %}
{% endblock %}

malasakit-django/pcari/templates/peer-responses.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'Tugon ng iba' %}{% endblock %}
{% block main-heading %}{% trans 'Tugon ng iba' %}{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      displayNoCurrentRespondentError();

      var current = Resource.load('current');
      pushResponse(Resource.load(current.data), false);

      var ratings = getResponseValue(['question-ratings']);
      for (var id in ratings) {
        var score = ratings[id];
        if (score !== SKIPPED) {
          $('#answer-' + id).text(score);
          if (score <= 1) {
            var emoticon = '/img/red-emoticon.png';
          } else if (score <= 2) {
            var emoticon = '/img/orange.png';
          } else if (score <= 3) {
            var emoticon = '/img/yellow-emoticon.jpg';
          } else {
            var emoticon = '/img/green-emoticon.png';
          }
          $('#answer-' + id).parent().prepend($('<img>').attr('src', STATIC_URL_ROOT + emoticon));
        } else {
          $('#answer-' + id).text(gettext('Skipped'));
          $('#answer-' + id).parent().prepend($('<img>').attr('src', STATIC_URL_ROOT + '/img/yellow-emoticon.jpg'));
        }
      }
    });
  </script>
{% endblock %}

{% block content %}
  {% if questions %}
    <p>
      {% blocktrans trimmed %}
        Sa ibaba, makikita mo kung paano sumagot ang iba pang mga kalahok sa mga tanong sa sarbey.
      {% endblocktrans %}
    </p>
    <div id="peer-responses">
      {% for question in questions %}
        {% with num_ratings=question.num_ratings mean=question.mean_score|floatformat %}
          <div class="boxed">
            <p>
              {% blocktrans trimmed %}
                <strong>{{ num_ratings }}</strong> katao na ang sumagot sa tanong na ito:
              {% endblocktrans %}
            </p>
            <blockquote>
              {% trans question.prompt %}
            </blockquote>
            {% if num_ratings %}
              <div class="bubbled">
                {% if question.mean_score <= 1.000 %}
                  <img src="{% static 'img/red-emoticon.png' %}">
                {% elif question.mean_score <= 2.000 %}
                  <img src="{% static 'img/yellow-emoticon.jpg' %}">
                {% else %}
                  <img src="{% static 'img/green-emoticon.png' %}">
                {% endif %}
                {% blocktrans trimmed %}
                  Karaniwang tugon: <strong>{{ mean }}</strong>
                {% endblocktrans %}
              </div>
            {% endif %}
            <div class="bubbled">
              {% with id=question.id %}
                {% trans 'Ang iyong tugon:'%} <strong id="answer-{{ id }}">{% trans 'Walang tugon' %}</strong>
              {% endwith %}
            </div>
          </div>
        {% endwith %}
      {% endfor %}
    </div>
  {% else %}
    <p class="error banner">{% trans 'There are not enough data to show how your responses compare to those of others.' %}</p>
  {% endif %}
  {% url 'pcari:end' as next_link %}
  {% include 'nav-buttons.html' %}
{% endblock %}

malasakit-django/pcari/templates/personal-information.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      displayNoCurrentRespondentError();

      function initializeField(inputElement, path, preprocess = x => x) {
        inputElement.on('input', function() {
          var value = preprocess($(this).val()) || null;
          if (value === null) {
            deleteResponseValue(path);
          } else {
            setResponseValue(path, value);
            inputElement.val(value);
          }
        });

        var value = getResponseValue(path);
        if (value !== undefined) {
          inputElement.val(value);
        }
      }

      var clipAge = makeClipped(1, 120);
      initializeField($('#age'), ['respondent-data', 'age'], function(rawValue) {
        var age = parseInt(rawValue);
        return isNaN(age) ? null : clipAge(age);
      });
      initializeField($('#gender'), ['respondent-data', 'gender']);

      setResponseValue(['respondent-data', 'submitted-personal-data'], true);

      var locations = Resource.load('locations').data;
      for (var id in locations) {
        var location = locations[id];
        $('#barangay').append($('<option value="' + id + '">' + location.division + '</option>'));
      }
      $('#barangay').append($('<option value="other">' + gettext('Other') + '</option>'));
      initializeField($('#barangay'), ['respondent-data', 'division']);

      var barangayExpand = function() {
        if ($('#barangay').val() === 'other') {
          var row = $('<tr id="barangay-name-row">').append('<td>Barangay Name</td>').append('<td><input type="text" id="barangay-name"></td>');
          $('#questions').append(row);
          initializeField($('#barangay-name'), ['respondent-data', 'new-division']);
        } else {
          $('#barangay-name-row').remove();
          deleteResponseValue(['respondent-data', 'new-division']);
        }
      };
      $('#barangay').on('input', barangayExpand);
      barangayExpand();

      initializeField($('#sector'), ['respondent-data', 'sector']);

      $('#next > a').on('click', function(event) {
        setResponseValue(['respondent-data', 'completed-survey'], true);
      });
    });
  </script>
{% endblock %}

{% block title %}{% trans 'Personal na Impormasyon' %}{% endblock %}
{% block main-heading %}{% trans 'Personal na Impormasyon' %}{% endblock %}

{% block content %}
  <div class="container">
    <p class="center">
      {% blocktrans trimmed %}
        Mangyaring sagutin ang hinihingi ng bawat item sa ibaba.
      {% endblocktrans %}
    </p>
  <table style="margin: 0 auto;">
    <tbody id="questions">
      <tr>
        <td>{% trans 'Edad' %}</td>
        <td><input id="age" type="number" min="1" max="120" onkeypress="validatePositiveInteger(event)"></td>
      </tr>
      <tr>
        <td>{% trans 'Kasarian' %}</td>
        <td>
          <select id="gender">
            <option value="M" selected>{% trans 'Lalake' %}</option>
            <option value="F">{% trans 'Babae' %}</option>
          </select>
        </td>
      </tr>
<!--      <tr>
        <td>{% trans 'Barangay' %}</td>
        <td>
          <select id="barangay">
            <option value="" selected>{% trans 'Select barangay' %}</option>
          </select>
        </td>
      </tr> -->
      <tr>
        <td>{% trans 'Kategorya' %}</td>
        <td>
          <select id="sector">
            <!--<option value="" selected>{% trans 'Piliin ang tanggapan' %}</option>-->
            <option value="Academic" selected>{% trans 'Academic Employee' %}</option>
            <option value="Non-academic">{% trans 'Non-academic Employee' %}</option>
            <option value="Student">{% trans 'Student' %}</option>
          </select>
        </td>
      </tr>
    </tbody>
  </table>
  {% url 'pcari:quantitative-questions' as next_link %}
  {% include 'nav-buttons.html' %}
{% endblock %}

malasakit-django/pcari/templates/qualitative-questions.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'Kuwalitatibong Tanong' %}{% endblock %}
{% block main-heading %}{% trans 'Ang Iyong mga Idea' %}{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function() {
      displayNoCurrentRespondentError();

      $('input[type=text], textarea').each(function() {
        var inputElement = $(this);
        var questionID = inputElement.attr('question-id');
        var path = ['comments', questionID];

        inputElement.on('input', function() {
          var text = inputElement.val().trim();
          setResponseValue(path, text);
        });

        var comment = getResponseValue(path);
        if (comment !== undefined) {
          inputElement.val(comment);
        }
      });
    });
  </script>
{% endblock %}

{% block content %}
  {% if questions %}
    {% if questions|length > 1 %}
      <ol id="qualitative-questions">
        {% for question in questions %}
          <li>
            {% trans question.prompt as prompt %}
            <p class="prompt">{{ prompt|linebreaksbr }}</p>
            <textarea question-id="{{ question.id }}" class="comment"></textarea>
          </li>
        {% endfor %}
      </ol>
    {% else %}
      {% with question=questions.0 %}
        {% trans question.prompt as prompt %}
        <p class="prompt">{{ prompt|linebreaksbr }}</p>
        <textarea question-id="{{ question.id }}" class="comment"></textarea>
      {% endwith %}
    {% endif %}
  {% else %}
    <p class="error banner">{% trans 'There are no qualitative questions at this time.' %}</p>
  {% endif %}
  {% url 'pcari:rate-comments' as previous_link %}
  {% url 'pcari:peer-responses' as next_link %}
  {% include 'nav-buttons.html' %}
{% endblock %}

malasakit-django/pcari/templates/rate-comments.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}

{% block title %}{% trans 'Puntusan ang mungkahi ng ibang kalahok' %}{% endblock %}
{% block main-heading %}{% trans 'Puntusan ang mungkahi ng ibang kalahok' %}{% endblock %}

{% block static-assets %}
  {{ block.super }}
  <script src="{% static 'js/d3.v4.min.js' %}"></script>
  <script src="{% static 'js/bloom.js' %}"></script>
{% endblock %}

{% block content %}
  <p>
    {% blocktrans trimmed %}
      Bawat icon sa ibaba ay mga mungkahing ibinigay ng ibang mga kalahok. Ang mga mungkahi na mas malapit sa isa't isa ay ibinigay ng mga kalahok na unang sumagot nito. 
    {% endblocktrans %}
  <p>
    {% blocktrans trimmed %}
   Mag-click ng isang icon upang makita ang mungkahi ng ibang kalahok. I-rate ito ayon sa antas ng inyong pagsang-ayon. Kinakailangan niyong mag-rate ng dalawang mungkahi upang makapagpatuloy. Pagkatapos nito, i-click ang "Susunod" sa ibaba. 
    {% endblocktrans %}
  </p>
  <div id="notice"></div>
  <svg id="bloom" width="100%"></svg>
  <div class="modal">
    <div class="modal-container">
      <p>{% trans 'Ang tanong:' %}</p>
      <blockquote id="question-prompt"></blockquote>
      <p>{% trans 'Ang sagot ng iba:' %}</p>
      <blockquote id="comment-message"></blockquote>

      <div class="range-container">
        <input id="quantitative-input" target-id="comment-rating" type="range"
               value="1" step="1" min="1" max="6">
        <span class="left-anchor">{% trans 'Lubos na di sumasang-ayon' %}</span>
        <span class="right-anchor">{% trans 'Lubos na sumasang-ayon' %}</span>
      </div>
      <p>
        {% trans 'Ang iyong sagot: ' %} <output id="quantitative-output"></output>.
      </p>

      <ul class="button-group">
        <li>
          <button id="skip" class="red">{% trans 'Laktawan' %}</button>
        </li>
        <li>
          <button id="submit" class="blue">{% trans 'Ipasa' %}</button>
        </li>
      </ul>
    </div>
  </div>
  {% url 'pcari:quantitative-questions' as previous_link %}
  {% url 'pcari:qualitative-questions' as next_link %}
  {% include 'nav-buttons.html' %}
{% endblock %}